import junit.framework.TestCase

class Day8Test : TestCase() {
    val input = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
    """.trimIndent().lines()
val input2= """
    T.........
    ...T......
    .T........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
""".trimIndent().lines()
    fun test1() {
        val ans = day8a(input)
        assertEquals(14, ans)
    }
    fun test2() {
        val ans = day8b(input2)
        assertEquals(9, ans)
    }
    fun test3() {
        val ans = day8b(input)
        assertEquals(34, ans)
    }
}
